"""empty message

Revision ID: 2e3434260fba
Revises: 635ef427bf6b
Create Date: 2025-12-24 21:29:01.711340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e3434260fba'
down_revision: Union[str, None] = '635ef427bf6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_user', sa.Column('password', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_user', 'password')
    # ### end Alembic commands ###
